import type { Config } from 'tailwindcss'
import animate from 'tailwindcss-animate'

const config: Config = {
  darkMode: ['class'],
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        workspace: 'hsl(var(--workspace))',
        'surface-subtle': 'hsl(var(--surface-subtle))',
        card: 'hsl(var(--card))',
        'card-foreground': 'hsl(var(--card-foreground))',
        popover: 'hsl(var(--popover))',
        'popover-foreground': 'hsl(var(--popover-foreground))',
        primary: 'hsl(var(--primary))',
        'primary-hover': 'hsl(var(--primary-hover))',
        'primary-active': 'hsl(var(--primary-active))',
        'primary-subtle': 'hsl(var(--primary-subtle))',
        'primary-foreground': 'hsl(var(--primary-foreground))',
        navy: 'hsl(var(--navy))',
        'navy-foreground': 'hsl(var(--navy-foreground))',
        'navy-muted': 'hsl(var(--navy-muted))',
        'light-blue': 'hsl(var(--light-blue))',
        'light-blue-foreground': 'hsl(var(--light-blue-foreground))',
        secondary: 'hsl(var(--secondary))',
        'secondary-foreground': 'hsl(var(--secondary-foreground))',
        muted: 'hsl(var(--muted))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        accent: 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        link: 'hsl(var(--link))',
        brand: 'hsl(var(--brand))',
        blue: {
          900: 'hsl(var(--blue-900))',
          700: 'hsl(var(--blue-700))',
          500: 'hsl(var(--blue-500))',
          300: 'hsl(var(--blue-300))',
          100: 'hsl(var(--blue-100))',
        },
        cyan: {
          900: 'hsl(var(--cyan-900))',
          700: 'hsl(var(--cyan-700))',
          500: 'hsl(var(--cyan-500))',
          300: 'hsl(var(--cyan-300))',
          100: 'hsl(var(--cyan-100))',
        },
        success: 'hsl(var(--success))',
        'success-500': 'hsl(var(--success-500))',
        'success-subtle': 'hsl(var(--success-subtle))',
        'success-foreground': 'hsl(var(--success-foreground))',
        warning: 'hsl(var(--warning))',
        'warning-500': 'hsl(var(--warning-500))',
        'warning-subtle': 'hsl(var(--warning-subtle))',
        'warning-foreground': 'hsl(var(--warning-foreground))',
        danger: 'hsl(var(--danger))',
        'danger-500': 'hsl(var(--danger-500))',
        'danger-hover': 'hsl(var(--danger-hover))',
        'danger-active': 'hsl(var(--danger-active))',
        'danger-subtle': 'hsl(var(--danger-subtle))',
        'danger-foreground': 'hsl(var(--danger-foreground))',
        info: 'hsl(var(--info))',
        'info-500': 'hsl(var(--info-500))',
        'info-subtle': 'hsl(var(--info-subtle))',
        'info-foreground': 'hsl(var(--info-foreground))',
        destructive: 'hsl(var(--destructive))',
        'destructive-foreground': 'hsl(var(--destructive-foreground))',
        'disabled-foreground': 'hsl(var(--disabled-foreground))',
        border: 'hsl(var(--border))',
        'border-strong': 'hsl(var(--border-strong))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: '9999px',
      },
      boxShadow: {
        popover: '0 8px 20px rgb(11 46 79 / 10%), 0 1px 3px rgb(11 46 79 / 8%)',
        dialog: '0 16px 40px rgb(11 46 79 / 14%), 0 2px 6px rgb(11 46 79 / 8%)',
      },
      fontFamily: {
        heading: ['var(--font-heading)', '"Segoe UI"', '"Helvetica Neue"', 'Arial', 'sans-serif'],
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [animate],
}

export default config
