-- Read-only, schema/security-only comparison; excludes Prisma ledger contents.
SELECT jsonb_build_object(
 'owners',(SELECT jsonb_agg(jsonb_build_array(n.nspname,c.relname,c.relkind,pg_get_userbyid(c.relowner)) ORDER BY n.nspname,c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN ('public','pathways') AND c.relkind IN ('r','S','v','m') AND c.relname<>'_prisma_migrations'),
 'functionOwners',(SELECT jsonb_agg(jsonb_build_array(p.proname,pg_get_function_identity_arguments(p.oid),pg_get_userbyid(p.proowner)) ORDER BY p.proname,pg_get_function_identity_arguments(p.oid)) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='pathways'),
 'extensions',(SELECT jsonb_agg(jsonb_build_array(extname,pg_get_userbyid(extowner)) ORDER BY extname) FROM pg_extension),
 'defaults',(SELECT jsonb_agg(jsonb_build_array(pg_get_userbyid(defaclrole),coalesce(n.nspname,''),defaclobjtype,defaclacl) ORDER BY defaclrole,defaclnamespace,defaclobjtype) FROM pg_default_acl d LEFT JOIN pg_namespace n ON n.oid=d.defaclnamespace),
 'tablePrivileges',(SELECT jsonb_agg(jsonb_build_array(n.nspname,c.relname,r.role_name,p.privilege,has_table_privilege(r.role_name,c.oid,p.privilege)) ORDER BY n.nspname,c.relname,r.role_name,p.privilege) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace CROSS JOIN (VALUES('pathways_runtime'),('anon'),('authenticated'),('service_role')) r(role_name) CROSS JOIN (VALUES('SELECT'),('INSERT'),('UPDATE'),('DELETE'),('TRUNCATE'),('REFERENCES'),('TRIGGER')) p(privilege) WHERE n.nspname IN ('public','pathways') AND c.relkind='r' AND c.relname<>'_prisma_migrations'),
 'columnPrivileges',(SELECT jsonb_agg(jsonb_build_array(n.nspname,c.relname,a.attname,r.role_name,p.privilege,has_column_privilege(r.role_name,c.oid,a.attnum,p.privilege)) ORDER BY n.nspname,c.relname,a.attnum,r.role_name,p.privilege) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped CROSS JOIN (VALUES('pathways_runtime'),('anon'),('authenticated'),('service_role')) r(role_name) CROSS JOIN (VALUES('SELECT'),('INSERT'),('UPDATE'),('REFERENCES')) p(privilege) WHERE n.nspname IN ('public','pathways') AND c.relkind='r' AND c.relname<>'_prisma_migrations')
)::text;
