-- Revised CSV contract. Baseline registration does not execute historical DDL.
-- Preserve business data, Auth, Storage, historical assignments and ledger rows.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';
DO $$ BEGIN
 IF current_user <> 'prisma' OR to_regprocedure('pathways.p09_can(text)') IS NULL
 OR NOT EXISTS(SELECT FROM pg_roles WHERE rolname='pathways_runtime' AND NOT rolsuper AND NOT rolbypassrls)
 THEN RAISE EXCEPTION '0027 requires verified 0026 state and migration identity'; END IF;
 IF EXISTS(SELECT FROM pathways.roles WHERE code NOT IN ('SYSTEM_ADMINISTRATOR','PROJECT_OFFICER','MONITORING_AND_EVALUATION_OFFICER','PROJECT_MANAGER','PROGRAM_MANAGER','GRANT_MANAGER') OR NOT is_active)
 OR EXISTS(SELECT FROM pathways.permissions WHERE NOT is_active) THEN RAISE EXCEPTION '0027 reference drift'; END IF;
END $$;
SELECT pg_advisory_xact_lock(505005,1);
INSERT INTO pathways.permissions(code,name) VALUES
('projects.read','projects.read'),
('projects.create','projects.create'),
('activities.read','activities.read'),
('activities.context.read','activities.context.read'),
('activities.create','activities.create'),
('activities.update','activities.update'),
('activities.proof.submit','activities.proof.submit'),
('journeys.read','journeys.read'),
('journeys.manage','journeys.manage'),
('participation.record','participation.record'),
('budgets.read','budgets.read'),
('budgets.create','budgets.create'),
('budgets.update','budgets.update'),
('expenses.read','expenses.read'),
('expenses.submit','expenses.submit'),
('expenses.verify','expenses.verify'),
('expenses.approve','expenses.approve'),
('monitoring.read','monitoring.read'),
('monitoring.review','monitoring.review'),
('rules.read','rules.read'),
('rules.create','rules.create'),
('rules.update','rules.update'),
('rules.activate','rules.activate'),
('alerts.read','alerts.read'),
('alerts.review','alerts.review'),
('alerts.outcome.record','alerts.outcome.record'),
('recommendations.read','recommendations.read'),
('recommendations.review','recommendations.review'),
('beneficiaries.records.read','beneficiaries.records.read'),
('beneficiaries.records.register','beneficiaries.records.register'),
('beneficiaries.profiles.update','beneficiaries.profiles.update'),
('beneficiaries.enrollments.manage','beneficiaries.enrollments.manage'),
('beneficiaries.identities.review','beneficiaries.identities.review'),
('beneficiaries.records.archive','beneficiaries.records.archive'),
('beneficiaries.aggregates.read','beneficiaries.aggregates.read'),
('recommendations.outcome.record','recommendations.outcome.record'),
('evaluations.submit','evaluations.submit'),
('evaluations.approve','evaluations.approve'),
('public.preview','public.preview'),
('public.publish','public.publish'),
('evidence.review','evidence.review'),
('indicators.create','indicators.create'),
('indicators.update','indicators.update'),
('collection.read','collection.read'),
('forms.read','forms.read'),
('forms.manage','forms.manage'),
('forms.publish','forms.publish'),
('submissions.write','submissions.write'),
('imports.read','imports.read'),
('imports.upload','imports.upload'),
('imports.review','imports.review'),
('imports.process','imports.process'),
('analytics.read','analytics.read'),
('reports.read','reports.read'),
('reports.project.read','reports.project.read'),
('reports.indicator.read','reports.indicator.read'),
('reports.beneficiary.read','reports.beneficiary.read'),
('users.authorize','users.authorize'),
('assignments.manage','assignments.manage'),
('settings.read','settings.read'),
('projects.detail.read','projects.detail.read'),
('projects.update','projects.update'),
('projects.archive','projects.archive'),
('activities.complete','activities.complete'),
('expenses.evidence.submit','expenses.evidence.submit'),
('indicators.read','indicators.read'),
('evaluations.archive','evaluations.archive'),
('evaluations.signoff','evaluations.signoff'),
('assessments.read','assessments.read'),
('public.approve','public.approve'),
('forms.generate','forms.generate'),
('forms.export','forms.export'),
('forms.import','forms.import'),
('imports.validate','imports.validate'),
('analytics.export','analytics.export'),
('reports.generate','reports.generate'),
('reports.export','reports.export'),
('audit.read','audit.read'),
('settings.configure','settings.configure'),
('backups.create','backups.create'),
('backups.restore','backups.restore'),
('profile.manage','profile.manage'),
('expenses.signoff','expenses.signoff'),
('programs.create','programs.create'),
('settings.labels.manage','settings.labels.manage'),
('assessments.detail.read','assessments.detail.read'),
('forms.archive','forms.archive'),
('indicators.archive','indicators.archive'),
('milestones.manage','milestones.manage'),
('activities.progress.update','activities.progress.update'),
('evidence.read','evidence.read'),
('activities.escalations.read','activities.escalations.read'),
('activities.escalations.raise','activities.escalations.raise'),
('forms.templates.import','forms.templates.import'),
('evaluations.weights.configure','evaluations.weights.configure'),
('dashboards.customize','dashboards.customize'),
('analytics.descriptive.read','analytics.descriptive.read'),
('analytics.saddd.read','analytics.saddd.read')
ON CONFLICT(code) DO NOTHING;
CREATE TEMP TABLE rbac_expected(role_code text,permission_code text,PRIMARY KEY(role_code,permission_code)) ON COMMIT DROP;
INSERT INTO rbac_expected VALUES
('SYSTEM_ADMINISTRATOR','projects.read'),
('PROJECT_OFFICER','projects.read'),
('MONITORING_AND_EVALUATION_OFFICER','projects.read'),
('PROJECT_MANAGER','projects.read'),
('PROGRAM_MANAGER','projects.read'),
('GRANT_MANAGER','projects.read'),
('PROJECT_MANAGER','projects.create'),
('SYSTEM_ADMINISTRATOR','activities.context.read'),
('PROJECT_OFFICER','activities.read'),
('MONITORING_AND_EVALUATION_OFFICER','activities.read'),
('PROJECT_MANAGER','activities.read'),
('PROJECT_OFFICER','activities.create'),
('PROJECT_MANAGER','activities.create'),
('PROJECT_MANAGER','activities.update'),
('PROJECT_OFFICER','activities.proof.submit'),
('PROJECT_MANAGER','activities.proof.submit'),
('SYSTEM_ADMINISTRATOR','journeys.read'),
('PROJECT_OFFICER','journeys.read'),
('MONITORING_AND_EVALUATION_OFFICER','journeys.read'),
('PROJECT_MANAGER','journeys.read'),
('SYSTEM_ADMINISTRATOR','journeys.manage'),
('MONITORING_AND_EVALUATION_OFFICER','journeys.manage'),
('PROJECT_MANAGER','journeys.manage'),
('PROJECT_OFFICER','participation.record'),
('MONITORING_AND_EVALUATION_OFFICER','participation.record'),
('PROJECT_MANAGER','participation.record'),
('PROJECT_MANAGER','budgets.read'),
('PROGRAM_MANAGER','budgets.read'),
('GRANT_MANAGER','budgets.read'),
('PROJECT_MANAGER','budgets.create'),
('PROGRAM_MANAGER','budgets.create'),
('GRANT_MANAGER','budgets.create'),
('PROJECT_MANAGER','budgets.update'),
('PROGRAM_MANAGER','budgets.update'),
('GRANT_MANAGER','budgets.update'),
('MONITORING_AND_EVALUATION_OFFICER','expenses.read'),
('PROJECT_MANAGER','expenses.read'),
('PROGRAM_MANAGER','expenses.read'),
('GRANT_MANAGER','expenses.read'),
('PROJECT_OFFICER','expenses.submit'),
('MONITORING_AND_EVALUATION_OFFICER','expenses.submit'),
('PROJECT_MANAGER','expenses.submit'),
('MONITORING_AND_EVALUATION_OFFICER','expenses.verify'),
('PROJECT_MANAGER','expenses.approve'),
('SYSTEM_ADMINISTRATOR','monitoring.read'),
('MONITORING_AND_EVALUATION_OFFICER','monitoring.read'),
('PROJECT_MANAGER','monitoring.read'),
('PROGRAM_MANAGER','monitoring.read'),
('GRANT_MANAGER','monitoring.read'),
('SYSTEM_ADMINISTRATOR','monitoring.review'),
('MONITORING_AND_EVALUATION_OFFICER','monitoring.review'),
('PROJECT_MANAGER','monitoring.review'),
('PROGRAM_MANAGER','monitoring.review'),
('GRANT_MANAGER','monitoring.review'),
('SYSTEM_ADMINISTRATOR','rules.read'),
('SYSTEM_ADMINISTRATOR','rules.create'),
('SYSTEM_ADMINISTRATOR','rules.update'),
('SYSTEM_ADMINISTRATOR','rules.activate'),
('SYSTEM_ADMINISTRATOR','alerts.read'),
('PROJECT_OFFICER','alerts.read'),
('MONITORING_AND_EVALUATION_OFFICER','alerts.read'),
('PROJECT_MANAGER','alerts.read'),
('PROGRAM_MANAGER','alerts.read'),
('GRANT_MANAGER','alerts.read'),
('SYSTEM_ADMINISTRATOR','alerts.review'),
('PROJECT_OFFICER','alerts.review'),
('MONITORING_AND_EVALUATION_OFFICER','alerts.review'),
('PROJECT_MANAGER','alerts.review'),
('PROGRAM_MANAGER','alerts.review'),
('GRANT_MANAGER','alerts.review'),
('SYSTEM_ADMINISTRATOR','alerts.outcome.record'),
('PROJECT_OFFICER','alerts.outcome.record'),
('MONITORING_AND_EVALUATION_OFFICER','alerts.outcome.record'),
('PROJECT_MANAGER','alerts.outcome.record'),
('PROGRAM_MANAGER','alerts.outcome.record'),
('GRANT_MANAGER','alerts.outcome.record'),
('SYSTEM_ADMINISTRATOR','recommendations.read'),
('PROJECT_OFFICER','recommendations.read'),
('MONITORING_AND_EVALUATION_OFFICER','recommendations.read'),
('PROJECT_MANAGER','recommendations.read'),
('PROGRAM_MANAGER','recommendations.read'),
('GRANT_MANAGER','recommendations.read'),
('SYSTEM_ADMINISTRATOR','recommendations.review'),
('PROJECT_OFFICER','recommendations.review'),
('MONITORING_AND_EVALUATION_OFFICER','recommendations.review'),
('PROJECT_MANAGER','recommendations.review'),
('PROGRAM_MANAGER','recommendations.review'),
('GRANT_MANAGER','recommendations.review'),
('PROJECT_OFFICER','beneficiaries.records.read'),
('MONITORING_AND_EVALUATION_OFFICER','beneficiaries.records.read'),
('PROJECT_MANAGER','beneficiaries.records.read'),
('PROJECT_OFFICER','beneficiaries.records.register'),
('MONITORING_AND_EVALUATION_OFFICER','beneficiaries.records.register'),
('PROJECT_MANAGER','beneficiaries.records.register'),
('PROJECT_OFFICER','beneficiaries.profiles.update'),
('MONITORING_AND_EVALUATION_OFFICER','beneficiaries.profiles.update'),
('PROJECT_MANAGER','beneficiaries.profiles.update'),
('PROJECT_OFFICER','beneficiaries.enrollments.manage'),
('MONITORING_AND_EVALUATION_OFFICER','beneficiaries.enrollments.manage'),
('PROJECT_MANAGER','beneficiaries.enrollments.manage'),
('SYSTEM_ADMINISTRATOR','beneficiaries.aggregates.read'),
('PROJECT_OFFICER','beneficiaries.aggregates.read'),
('MONITORING_AND_EVALUATION_OFFICER','beneficiaries.aggregates.read'),
('PROJECT_MANAGER','beneficiaries.aggregates.read'),
('PROGRAM_MANAGER','beneficiaries.aggregates.read'),
('GRANT_MANAGER','beneficiaries.aggregates.read'),
('SYSTEM_ADMINISTRATOR','recommendations.outcome.record'),
('PROJECT_OFFICER','recommendations.outcome.record'),
('MONITORING_AND_EVALUATION_OFFICER','recommendations.outcome.record'),
('PROJECT_MANAGER','recommendations.outcome.record'),
('PROGRAM_MANAGER','recommendations.outcome.record'),
('GRANT_MANAGER','recommendations.outcome.record'),
('SYSTEM_ADMINISTRATOR','public.preview'),
('PROJECT_MANAGER','public.preview'),
('PROGRAM_MANAGER','public.preview'),
('GRANT_MANAGER','public.preview'),
('SYSTEM_ADMINISTRATOR','public.publish'),
('PROJECT_MANAGER','public.publish'),
('PROGRAM_MANAGER','public.publish'),
('GRANT_MANAGER','public.publish'),
('MONITORING_AND_EVALUATION_OFFICER','evidence.review'),
('SYSTEM_ADMINISTRATOR','indicators.create'),
('MONITORING_AND_EVALUATION_OFFICER','indicators.create'),
('PROJECT_MANAGER','indicators.create'),
('SYSTEM_ADMINISTRATOR','indicators.update'),
('MONITORING_AND_EVALUATION_OFFICER','indicators.update'),
('PROJECT_MANAGER','indicators.update'),
('SYSTEM_ADMINISTRATOR','collection.read'),
('PROJECT_OFFICER','collection.read'),
('MONITORING_AND_EVALUATION_OFFICER','collection.read'),
('SYSTEM_ADMINISTRATOR','forms.read'),
('PROJECT_OFFICER','forms.read'),
('MONITORING_AND_EVALUATION_OFFICER','forms.read'),
('SYSTEM_ADMINISTRATOR','forms.manage'),
('MONITORING_AND_EVALUATION_OFFICER','forms.manage'),
('SYSTEM_ADMINISTRATOR','forms.publish'),
('MONITORING_AND_EVALUATION_OFFICER','forms.publish'),
('PROJECT_OFFICER','submissions.write'),
('MONITORING_AND_EVALUATION_OFFICER','submissions.write'),
('SYSTEM_ADMINISTRATOR','imports.read'),
('PROJECT_OFFICER','imports.read'),
('MONITORING_AND_EVALUATION_OFFICER','imports.read'),
('SYSTEM_ADMINISTRATOR','imports.upload'),
('PROJECT_OFFICER','imports.upload'),
('MONITORING_AND_EVALUATION_OFFICER','imports.upload'),
('SYSTEM_ADMINISTRATOR','imports.review'),
('MONITORING_AND_EVALUATION_OFFICER','imports.review'),
('SYSTEM_ADMINISTRATOR','imports.process'),
('PROJECT_OFFICER','imports.process'),
('MONITORING_AND_EVALUATION_OFFICER','imports.process'),
('SYSTEM_ADMINISTRATOR','analytics.read'),
('PROJECT_OFFICER','analytics.read'),
('MONITORING_AND_EVALUATION_OFFICER','analytics.read'),
('PROJECT_MANAGER','analytics.read'),
('PROGRAM_MANAGER','analytics.read'),
('GRANT_MANAGER','analytics.read'),
('SYSTEM_ADMINISTRATOR','reports.read'),
('PROJECT_OFFICER','reports.read'),
('MONITORING_AND_EVALUATION_OFFICER','reports.read'),
('PROJECT_MANAGER','reports.read'),
('PROGRAM_MANAGER','reports.read'),
('GRANT_MANAGER','reports.read'),
('SYSTEM_ADMINISTRATOR','reports.project.read'),
('PROJECT_OFFICER','reports.project.read'),
('MONITORING_AND_EVALUATION_OFFICER','reports.project.read'),
('PROJECT_MANAGER','reports.project.read'),
('PROGRAM_MANAGER','reports.project.read'),
('GRANT_MANAGER','reports.project.read'),
('SYSTEM_ADMINISTRATOR','reports.indicator.read'),
('PROJECT_OFFICER','reports.indicator.read'),
('MONITORING_AND_EVALUATION_OFFICER','reports.indicator.read'),
('PROJECT_MANAGER','reports.indicator.read'),
('PROGRAM_MANAGER','reports.indicator.read'),
('GRANT_MANAGER','reports.indicator.read'),
('PROJECT_OFFICER','reports.beneficiary.read'),
('MONITORING_AND_EVALUATION_OFFICER','reports.beneficiary.read'),
('PROJECT_MANAGER','reports.beneficiary.read'),
('SYSTEM_ADMINISTRATOR','users.authorize'),
('PROJECT_MANAGER','users.authorize'),
('PROGRAM_MANAGER','users.authorize'),
('SYSTEM_ADMINISTRATOR','assignments.manage'),
('PROJECT_MANAGER','assignments.manage'),
('PROGRAM_MANAGER','assignments.manage'),
('SYSTEM_ADMINISTRATOR','settings.read'),
('PROJECT_OFFICER','settings.read'),
('MONITORING_AND_EVALUATION_OFFICER','settings.read'),
('PROJECT_MANAGER','settings.read'),
('PROGRAM_MANAGER','settings.read'),
('GRANT_MANAGER','settings.read'),
('SYSTEM_ADMINISTRATOR','projects.detail.read'),
('PROJECT_OFFICER','projects.detail.read'),
('MONITORING_AND_EVALUATION_OFFICER','projects.detail.read'),
('PROJECT_MANAGER','projects.detail.read'),
('PROGRAM_MANAGER','projects.detail.read'),
('GRANT_MANAGER','projects.detail.read'),
('PROJECT_MANAGER','projects.update'),
('SYSTEM_ADMINISTRATOR','projects.archive'),
('PROJECT_MANAGER','projects.archive'),
('PROGRAM_MANAGER','projects.archive'),
('GRANT_MANAGER','projects.archive'),
('PROJECT_OFFICER','activities.complete'),
('MONITORING_AND_EVALUATION_OFFICER','activities.complete'),
('PROJECT_MANAGER','activities.complete'),
('PROJECT_OFFICER','expenses.evidence.submit'),
('MONITORING_AND_EVALUATION_OFFICER','expenses.evidence.submit'),
('PROJECT_MANAGER','expenses.evidence.submit'),
('SYSTEM_ADMINISTRATOR','indicators.read'),
('MONITORING_AND_EVALUATION_OFFICER','indicators.read'),
('PROJECT_MANAGER','indicators.read'),
('SYSTEM_ADMINISTRATOR','assessments.read'),
('PROJECT_OFFICER','assessments.read'),
('MONITORING_AND_EVALUATION_OFFICER','assessments.read'),
('PROJECT_MANAGER','assessments.read'),
('PROGRAM_MANAGER','assessments.read'),
('GRANT_MANAGER','assessments.read'),
('SYSTEM_ADMINISTRATOR','public.approve'),
('PROJECT_MANAGER','public.approve'),
('PROGRAM_MANAGER','public.approve'),
('GRANT_MANAGER','public.approve'),
('SYSTEM_ADMINISTRATOR','forms.generate'),
('PROJECT_OFFICER','forms.generate'),
('MONITORING_AND_EVALUATION_OFFICER','forms.generate'),
('SYSTEM_ADMINISTRATOR','forms.export'),
('MONITORING_AND_EVALUATION_OFFICER','forms.export'),
('SYSTEM_ADMINISTRATOR','forms.import'),
('PROJECT_OFFICER','forms.import'),
('MONITORING_AND_EVALUATION_OFFICER','forms.import'),
('SYSTEM_ADMINISTRATOR','imports.validate'),
('PROJECT_OFFICER','imports.validate'),
('MONITORING_AND_EVALUATION_OFFICER','imports.validate'),
('SYSTEM_ADMINISTRATOR','analytics.export'),
('MONITORING_AND_EVALUATION_OFFICER','analytics.export'),
('PROJECT_MANAGER','analytics.export'),
('PROGRAM_MANAGER','analytics.export'),
('GRANT_MANAGER','analytics.export'),
('SYSTEM_ADMINISTRATOR','reports.generate'),
('PROJECT_OFFICER','reports.generate'),
('MONITORING_AND_EVALUATION_OFFICER','reports.generate'),
('PROJECT_MANAGER','reports.generate'),
('PROGRAM_MANAGER','reports.generate'),
('GRANT_MANAGER','reports.generate'),
('SYSTEM_ADMINISTRATOR','reports.export'),
('PROJECT_OFFICER','reports.export'),
('MONITORING_AND_EVALUATION_OFFICER','reports.export'),
('PROJECT_MANAGER','reports.export'),
('PROGRAM_MANAGER','reports.export'),
('GRANT_MANAGER','reports.export'),
('SYSTEM_ADMINISTRATOR','audit.read'),
('PROJECT_MANAGER','audit.read'),
('PROGRAM_MANAGER','audit.read'),
('SYSTEM_ADMINISTRATOR','settings.configure'),
('SYSTEM_ADMINISTRATOR','backups.create'),
('SYSTEM_ADMINISTRATOR','backups.restore'),
('SYSTEM_ADMINISTRATOR','profile.manage'),
('PROJECT_OFFICER','profile.manage'),
('MONITORING_AND_EVALUATION_OFFICER','profile.manage'),
('PROJECT_MANAGER','profile.manage'),
('PROGRAM_MANAGER','profile.manage'),
('GRANT_MANAGER','profile.manage'),
('PROGRAM_MANAGER','expenses.signoff'),
('GRANT_MANAGER','expenses.signoff'),
('PROJECT_OFFICER','assessments.detail.read'),
('MONITORING_AND_EVALUATION_OFFICER','assessments.detail.read'),
('PROJECT_MANAGER','assessments.detail.read'),
('PROJECT_OFFICER','activities.progress.update'),
('MONITORING_AND_EVALUATION_OFFICER','activities.progress.update'),
('PROJECT_MANAGER','activities.progress.update'),
('SYSTEM_ADMINISTRATOR','evidence.read'),
('PROJECT_OFFICER','evidence.read'),
('MONITORING_AND_EVALUATION_OFFICER','evidence.read'),
('PROJECT_MANAGER','evidence.read'),
('PROGRAM_MANAGER','evidence.read'),
('GRANT_MANAGER','evidence.read'),
('SYSTEM_ADMINISTRATOR','activities.escalations.read'),
('PROJECT_OFFICER','activities.escalations.read'),
('MONITORING_AND_EVALUATION_OFFICER','activities.escalations.read'),
('PROJECT_MANAGER','activities.escalations.read'),
('PROGRAM_MANAGER','activities.escalations.read'),
('GRANT_MANAGER','activities.escalations.read'),
('SYSTEM_ADMINISTRATOR','activities.escalations.raise'),
('PROJECT_OFFICER','activities.escalations.raise'),
('MONITORING_AND_EVALUATION_OFFICER','activities.escalations.raise'),
('PROJECT_MANAGER','activities.escalations.raise'),
('PROGRAM_MANAGER','activities.escalations.raise'),
('GRANT_MANAGER','activities.escalations.raise'),
('SYSTEM_ADMINISTRATOR','forms.templates.import'),
('MONITORING_AND_EVALUATION_OFFICER','forms.templates.import'),
('SYSTEM_ADMINISTRATOR','evaluations.weights.configure'),
('MONITORING_AND_EVALUATION_OFFICER','evaluations.weights.configure'),
('SYSTEM_ADMINISTRATOR','dashboards.customize'),
('PROJECT_OFFICER','dashboards.customize'),
('MONITORING_AND_EVALUATION_OFFICER','dashboards.customize'),
('PROJECT_MANAGER','dashboards.customize'),
('PROGRAM_MANAGER','dashboards.customize'),
('GRANT_MANAGER','dashboards.customize'),
('SYSTEM_ADMINISTRATOR','analytics.descriptive.read'),
('MONITORING_AND_EVALUATION_OFFICER','analytics.descriptive.read'),
('PROJECT_MANAGER','analytics.descriptive.read'),
('PROGRAM_MANAGER','analytics.descriptive.read'),
('GRANT_MANAGER','analytics.descriptive.read'),
('SYSTEM_ADMINISTRATOR','analytics.saddd.read'),
('PROJECT_OFFICER','analytics.saddd.read'),
('MONITORING_AND_EVALUATION_OFFICER','analytics.saddd.read'),
('PROJECT_MANAGER','analytics.saddd.read'),
('PROGRAM_MANAGER','analytics.saddd.read'),
('GRANT_MANAGER','analytics.saddd.read');
DELETE FROM pathways.role_permissions rp USING pathways.roles r,pathways.permissions p
WHERE rp.role_id=r.id AND rp.permission_id=p.id
  AND NOT EXISTS(SELECT FROM rbac_expected e WHERE e.role_code=r.code AND e.permission_code=p.code);
INSERT INTO pathways.role_permissions(role_id,permission_id)
SELECT r.id,p.id FROM rbac_expected e JOIN pathways.roles r ON r.code=e.role_code JOIN pathways.permissions p ON p.code=e.permission_code
ON CONFLICT(role_id,permission_id) DO NOTHING;

CREATE OR REPLACE FUNCTION pathways.p09_role_allows(role_code text,wanted_permission text) RETURNS boolean
LANGUAGE sql IMMUTABLE SECURITY INVOKER SET search_path='' AS $matrix$
 SELECT EXISTS(SELECT FROM (VALUES
('SYSTEM_ADMINISTRATOR','projects.read'),
('PROJECT_OFFICER','projects.read'),
('MONITORING_AND_EVALUATION_OFFICER','projects.read'),
('PROJECT_MANAGER','projects.read'),
('PROGRAM_MANAGER','projects.read'),
('GRANT_MANAGER','projects.read'),
('PROJECT_MANAGER','projects.create'),
('SYSTEM_ADMINISTRATOR','activities.context.read'),
('PROJECT_OFFICER','activities.read'),
('MONITORING_AND_EVALUATION_OFFICER','activities.read'),
('PROJECT_MANAGER','activities.read'),
('PROJECT_OFFICER','activities.create'),
('PROJECT_MANAGER','activities.create'),
('PROJECT_MANAGER','activities.update'),
('PROJECT_OFFICER','activities.proof.submit'),
('PROJECT_MANAGER','activities.proof.submit'),
('SYSTEM_ADMINISTRATOR','journeys.read'),
('PROJECT_OFFICER','journeys.read'),
('MONITORING_AND_EVALUATION_OFFICER','journeys.read'),
('PROJECT_MANAGER','journeys.read'),
('SYSTEM_ADMINISTRATOR','journeys.manage'),
('MONITORING_AND_EVALUATION_OFFICER','journeys.manage'),
('PROJECT_MANAGER','journeys.manage'),
('PROJECT_OFFICER','participation.record'),
('MONITORING_AND_EVALUATION_OFFICER','participation.record'),
('PROJECT_MANAGER','participation.record'),
('PROJECT_MANAGER','budgets.read'),
('PROGRAM_MANAGER','budgets.read'),
('GRANT_MANAGER','budgets.read'),
('PROJECT_MANAGER','budgets.create'),
('PROGRAM_MANAGER','budgets.create'),
('GRANT_MANAGER','budgets.create'),
('PROJECT_MANAGER','budgets.update'),
('PROGRAM_MANAGER','budgets.update'),
('GRANT_MANAGER','budgets.update'),
('MONITORING_AND_EVALUATION_OFFICER','expenses.read'),
('PROJECT_MANAGER','expenses.read'),
('PROGRAM_MANAGER','expenses.read'),
('GRANT_MANAGER','expenses.read'),
('PROJECT_OFFICER','expenses.submit'),
('MONITORING_AND_EVALUATION_OFFICER','expenses.submit'),
('PROJECT_MANAGER','expenses.submit'),
('MONITORING_AND_EVALUATION_OFFICER','expenses.verify'),
('PROJECT_MANAGER','expenses.approve'),
('SYSTEM_ADMINISTRATOR','monitoring.read'),
('MONITORING_AND_EVALUATION_OFFICER','monitoring.read'),
('PROJECT_MANAGER','monitoring.read'),
('PROGRAM_MANAGER','monitoring.read'),
('GRANT_MANAGER','monitoring.read'),
('SYSTEM_ADMINISTRATOR','monitoring.review'),
('MONITORING_AND_EVALUATION_OFFICER','monitoring.review'),
('PROJECT_MANAGER','monitoring.review'),
('PROGRAM_MANAGER','monitoring.review'),
('GRANT_MANAGER','monitoring.review'),
('SYSTEM_ADMINISTRATOR','rules.read'),
('SYSTEM_ADMINISTRATOR','rules.create'),
('SYSTEM_ADMINISTRATOR','rules.update'),
('SYSTEM_ADMINISTRATOR','rules.activate'),
('SYSTEM_ADMINISTRATOR','alerts.read'),
('PROJECT_OFFICER','alerts.read'),
('MONITORING_AND_EVALUATION_OFFICER','alerts.read'),
('PROJECT_MANAGER','alerts.read'),
('PROGRAM_MANAGER','alerts.read'),
('GRANT_MANAGER','alerts.read'),
('SYSTEM_ADMINISTRATOR','alerts.review'),
('PROJECT_OFFICER','alerts.review'),
('MONITORING_AND_EVALUATION_OFFICER','alerts.review'),
('PROJECT_MANAGER','alerts.review'),
('PROGRAM_MANAGER','alerts.review'),
('GRANT_MANAGER','alerts.review'),
('SYSTEM_ADMINISTRATOR','alerts.outcome.record'),
('PROJECT_OFFICER','alerts.outcome.record'),
('MONITORING_AND_EVALUATION_OFFICER','alerts.outcome.record'),
('PROJECT_MANAGER','alerts.outcome.record'),
('PROGRAM_MANAGER','alerts.outcome.record'),
('GRANT_MANAGER','alerts.outcome.record'),
('SYSTEM_ADMINISTRATOR','recommendations.read'),
('PROJECT_OFFICER','recommendations.read'),
('MONITORING_AND_EVALUATION_OFFICER','recommendations.read'),
('PROJECT_MANAGER','recommendations.read'),
('PROGRAM_MANAGER','recommendations.read'),
('GRANT_MANAGER','recommendations.read'),
('SYSTEM_ADMINISTRATOR','recommendations.review'),
('PROJECT_OFFICER','recommendations.review'),
('MONITORING_AND_EVALUATION_OFFICER','recommendations.review'),
('PROJECT_MANAGER','recommendations.review'),
('PROGRAM_MANAGER','recommendations.review'),
('GRANT_MANAGER','recommendations.review'),
('PROJECT_OFFICER','beneficiaries.records.read'),
('MONITORING_AND_EVALUATION_OFFICER','beneficiaries.records.read'),
('PROJECT_MANAGER','beneficiaries.records.read'),
('PROJECT_OFFICER','beneficiaries.records.register'),
('MONITORING_AND_EVALUATION_OFFICER','beneficiaries.records.register'),
('PROJECT_MANAGER','beneficiaries.records.register'),
('PROJECT_OFFICER','beneficiaries.profiles.update'),
('MONITORING_AND_EVALUATION_OFFICER','beneficiaries.profiles.update'),
('PROJECT_MANAGER','beneficiaries.profiles.update'),
('PROJECT_OFFICER','beneficiaries.enrollments.manage'),
('MONITORING_AND_EVALUATION_OFFICER','beneficiaries.enrollments.manage'),
('PROJECT_MANAGER','beneficiaries.enrollments.manage'),
('SYSTEM_ADMINISTRATOR','beneficiaries.aggregates.read'),
('PROJECT_OFFICER','beneficiaries.aggregates.read'),
('MONITORING_AND_EVALUATION_OFFICER','beneficiaries.aggregates.read'),
('PROJECT_MANAGER','beneficiaries.aggregates.read'),
('PROGRAM_MANAGER','beneficiaries.aggregates.read'),
('GRANT_MANAGER','beneficiaries.aggregates.read'),
('SYSTEM_ADMINISTRATOR','recommendations.outcome.record'),
('PROJECT_OFFICER','recommendations.outcome.record'),
('MONITORING_AND_EVALUATION_OFFICER','recommendations.outcome.record'),
('PROJECT_MANAGER','recommendations.outcome.record'),
('PROGRAM_MANAGER','recommendations.outcome.record'),
('GRANT_MANAGER','recommendations.outcome.record'),
('SYSTEM_ADMINISTRATOR','public.preview'),
('PROJECT_MANAGER','public.preview'),
('PROGRAM_MANAGER','public.preview'),
('GRANT_MANAGER','public.preview'),
('SYSTEM_ADMINISTRATOR','public.publish'),
('PROJECT_MANAGER','public.publish'),
('PROGRAM_MANAGER','public.publish'),
('GRANT_MANAGER','public.publish'),
('MONITORING_AND_EVALUATION_OFFICER','evidence.review'),
('SYSTEM_ADMINISTRATOR','indicators.create'),
('MONITORING_AND_EVALUATION_OFFICER','indicators.create'),
('PROJECT_MANAGER','indicators.create'),
('SYSTEM_ADMINISTRATOR','indicators.update'),
('MONITORING_AND_EVALUATION_OFFICER','indicators.update'),
('PROJECT_MANAGER','indicators.update'),
('SYSTEM_ADMINISTRATOR','collection.read'),
('PROJECT_OFFICER','collection.read'),
('MONITORING_AND_EVALUATION_OFFICER','collection.read'),
('SYSTEM_ADMINISTRATOR','forms.read'),
('PROJECT_OFFICER','forms.read'),
('MONITORING_AND_EVALUATION_OFFICER','forms.read'),
('SYSTEM_ADMINISTRATOR','forms.manage'),
('MONITORING_AND_EVALUATION_OFFICER','forms.manage'),
('SYSTEM_ADMINISTRATOR','forms.publish'),
('MONITORING_AND_EVALUATION_OFFICER','forms.publish'),
('PROJECT_OFFICER','submissions.write'),
('MONITORING_AND_EVALUATION_OFFICER','submissions.write'),
('SYSTEM_ADMINISTRATOR','imports.read'),
('PROJECT_OFFICER','imports.read'),
('MONITORING_AND_EVALUATION_OFFICER','imports.read'),
('SYSTEM_ADMINISTRATOR','imports.upload'),
('PROJECT_OFFICER','imports.upload'),
('MONITORING_AND_EVALUATION_OFFICER','imports.upload'),
('SYSTEM_ADMINISTRATOR','imports.review'),
('MONITORING_AND_EVALUATION_OFFICER','imports.review'),
('SYSTEM_ADMINISTRATOR','imports.process'),
('PROJECT_OFFICER','imports.process'),
('MONITORING_AND_EVALUATION_OFFICER','imports.process'),
('SYSTEM_ADMINISTRATOR','analytics.read'),
('PROJECT_OFFICER','analytics.read'),
('MONITORING_AND_EVALUATION_OFFICER','analytics.read'),
('PROJECT_MANAGER','analytics.read'),
('PROGRAM_MANAGER','analytics.read'),
('GRANT_MANAGER','analytics.read'),
('SYSTEM_ADMINISTRATOR','reports.read'),
('PROJECT_OFFICER','reports.read'),
('MONITORING_AND_EVALUATION_OFFICER','reports.read'),
('PROJECT_MANAGER','reports.read'),
('PROGRAM_MANAGER','reports.read'),
('GRANT_MANAGER','reports.read'),
('SYSTEM_ADMINISTRATOR','reports.project.read'),
('PROJECT_OFFICER','reports.project.read'),
('MONITORING_AND_EVALUATION_OFFICER','reports.project.read'),
('PROJECT_MANAGER','reports.project.read'),
('PROGRAM_MANAGER','reports.project.read'),
('GRANT_MANAGER','reports.project.read'),
('SYSTEM_ADMINISTRATOR','reports.indicator.read'),
('PROJECT_OFFICER','reports.indicator.read'),
('MONITORING_AND_EVALUATION_OFFICER','reports.indicator.read'),
('PROJECT_MANAGER','reports.indicator.read'),
('PROGRAM_MANAGER','reports.indicator.read'),
('GRANT_MANAGER','reports.indicator.read'),
('PROJECT_OFFICER','reports.beneficiary.read'),
('MONITORING_AND_EVALUATION_OFFICER','reports.beneficiary.read'),
('PROJECT_MANAGER','reports.beneficiary.read'),
('SYSTEM_ADMINISTRATOR','users.authorize'),
('PROJECT_MANAGER','users.authorize'),
('PROGRAM_MANAGER','users.authorize'),
('SYSTEM_ADMINISTRATOR','assignments.manage'),
('PROJECT_MANAGER','assignments.manage'),
('PROGRAM_MANAGER','assignments.manage'),
('SYSTEM_ADMINISTRATOR','settings.read'),
('PROJECT_OFFICER','settings.read'),
('MONITORING_AND_EVALUATION_OFFICER','settings.read'),
('PROJECT_MANAGER','settings.read'),
('PROGRAM_MANAGER','settings.read'),
('GRANT_MANAGER','settings.read'),
('SYSTEM_ADMINISTRATOR','projects.detail.read'),
('PROJECT_OFFICER','projects.detail.read'),
('MONITORING_AND_EVALUATION_OFFICER','projects.detail.read'),
('PROJECT_MANAGER','projects.detail.read'),
('PROGRAM_MANAGER','projects.detail.read'),
('GRANT_MANAGER','projects.detail.read'),
('PROJECT_MANAGER','projects.update'),
('SYSTEM_ADMINISTRATOR','projects.archive'),
('PROJECT_MANAGER','projects.archive'),
('PROGRAM_MANAGER','projects.archive'),
('GRANT_MANAGER','projects.archive'),
('PROJECT_OFFICER','activities.complete'),
('MONITORING_AND_EVALUATION_OFFICER','activities.complete'),
('PROJECT_MANAGER','activities.complete'),
('PROJECT_OFFICER','expenses.evidence.submit'),
('MONITORING_AND_EVALUATION_OFFICER','expenses.evidence.submit'),
('PROJECT_MANAGER','expenses.evidence.submit'),
('SYSTEM_ADMINISTRATOR','indicators.read'),
('MONITORING_AND_EVALUATION_OFFICER','indicators.read'),
('PROJECT_MANAGER','indicators.read'),
('SYSTEM_ADMINISTRATOR','assessments.read'),
('PROJECT_OFFICER','assessments.read'),
('MONITORING_AND_EVALUATION_OFFICER','assessments.read'),
('PROJECT_MANAGER','assessments.read'),
('PROGRAM_MANAGER','assessments.read'),
('GRANT_MANAGER','assessments.read'),
('SYSTEM_ADMINISTRATOR','public.approve'),
('PROJECT_MANAGER','public.approve'),
('PROGRAM_MANAGER','public.approve'),
('GRANT_MANAGER','public.approve'),
('SYSTEM_ADMINISTRATOR','forms.generate'),
('PROJECT_OFFICER','forms.generate'),
('MONITORING_AND_EVALUATION_OFFICER','forms.generate'),
('SYSTEM_ADMINISTRATOR','forms.export'),
('MONITORING_AND_EVALUATION_OFFICER','forms.export'),
('SYSTEM_ADMINISTRATOR','forms.import'),
('PROJECT_OFFICER','forms.import'),
('MONITORING_AND_EVALUATION_OFFICER','forms.import'),
('SYSTEM_ADMINISTRATOR','imports.validate'),
('PROJECT_OFFICER','imports.validate'),
('MONITORING_AND_EVALUATION_OFFICER','imports.validate'),
('SYSTEM_ADMINISTRATOR','analytics.export'),
('MONITORING_AND_EVALUATION_OFFICER','analytics.export'),
('PROJECT_MANAGER','analytics.export'),
('PROGRAM_MANAGER','analytics.export'),
('GRANT_MANAGER','analytics.export'),
('SYSTEM_ADMINISTRATOR','reports.generate'),
('PROJECT_OFFICER','reports.generate'),
('MONITORING_AND_EVALUATION_OFFICER','reports.generate'),
('PROJECT_MANAGER','reports.generate'),
('PROGRAM_MANAGER','reports.generate'),
('GRANT_MANAGER','reports.generate'),
('SYSTEM_ADMINISTRATOR','reports.export'),
('PROJECT_OFFICER','reports.export'),
('MONITORING_AND_EVALUATION_OFFICER','reports.export'),
('PROJECT_MANAGER','reports.export'),
('PROGRAM_MANAGER','reports.export'),
('GRANT_MANAGER','reports.export'),
('SYSTEM_ADMINISTRATOR','audit.read'),
('PROJECT_MANAGER','audit.read'),
('PROGRAM_MANAGER','audit.read'),
('SYSTEM_ADMINISTRATOR','settings.configure'),
('SYSTEM_ADMINISTRATOR','backups.create'),
('SYSTEM_ADMINISTRATOR','backups.restore'),
('SYSTEM_ADMINISTRATOR','profile.manage'),
('PROJECT_OFFICER','profile.manage'),
('MONITORING_AND_EVALUATION_OFFICER','profile.manage'),
('PROJECT_MANAGER','profile.manage'),
('PROGRAM_MANAGER','profile.manage'),
('GRANT_MANAGER','profile.manage'),
('PROGRAM_MANAGER','expenses.signoff'),
('GRANT_MANAGER','expenses.signoff'),
('PROJECT_OFFICER','assessments.detail.read'),
('MONITORING_AND_EVALUATION_OFFICER','assessments.detail.read'),
('PROJECT_MANAGER','assessments.detail.read'),
('PROJECT_OFFICER','activities.progress.update'),
('MONITORING_AND_EVALUATION_OFFICER','activities.progress.update'),
('PROJECT_MANAGER','activities.progress.update'),
('SYSTEM_ADMINISTRATOR','evidence.read'),
('PROJECT_OFFICER','evidence.read'),
('MONITORING_AND_EVALUATION_OFFICER','evidence.read'),
('PROJECT_MANAGER','evidence.read'),
('PROGRAM_MANAGER','evidence.read'),
('GRANT_MANAGER','evidence.read'),
('SYSTEM_ADMINISTRATOR','activities.escalations.read'),
('PROJECT_OFFICER','activities.escalations.read'),
('MONITORING_AND_EVALUATION_OFFICER','activities.escalations.read'),
('PROJECT_MANAGER','activities.escalations.read'),
('PROGRAM_MANAGER','activities.escalations.read'),
('GRANT_MANAGER','activities.escalations.read'),
('SYSTEM_ADMINISTRATOR','activities.escalations.raise'),
('PROJECT_OFFICER','activities.escalations.raise'),
('MONITORING_AND_EVALUATION_OFFICER','activities.escalations.raise'),
('PROJECT_MANAGER','activities.escalations.raise'),
('PROGRAM_MANAGER','activities.escalations.raise'),
('GRANT_MANAGER','activities.escalations.raise'),
('SYSTEM_ADMINISTRATOR','forms.templates.import'),
('MONITORING_AND_EVALUATION_OFFICER','forms.templates.import'),
('SYSTEM_ADMINISTRATOR','evaluations.weights.configure'),
('MONITORING_AND_EVALUATION_OFFICER','evaluations.weights.configure'),
('SYSTEM_ADMINISTRATOR','dashboards.customize'),
('PROJECT_OFFICER','dashboards.customize'),
('MONITORING_AND_EVALUATION_OFFICER','dashboards.customize'),
('PROJECT_MANAGER','dashboards.customize'),
('PROGRAM_MANAGER','dashboards.customize'),
('GRANT_MANAGER','dashboards.customize'),
('SYSTEM_ADMINISTRATOR','analytics.descriptive.read'),
('MONITORING_AND_EVALUATION_OFFICER','analytics.descriptive.read'),
('PROJECT_MANAGER','analytics.descriptive.read'),
('PROGRAM_MANAGER','analytics.descriptive.read'),
('GRANT_MANAGER','analytics.descriptive.read'),
('SYSTEM_ADMINISTRATOR','analytics.saddd.read'),
('PROJECT_OFFICER','analytics.saddd.read'),
('MONITORING_AND_EVALUATION_OFFICER','analytics.saddd.read'),
('PROJECT_MANAGER','analytics.saddd.read'),
('PROGRAM_MANAGER','analytics.saddd.read'),
('GRANT_MANAGER','analytics.saddd.read')) allowed(role_code,permission_code)
 WHERE allowed.role_code=$1 AND allowed.permission_code=$2)
$matrix$;
REVOKE ALL ON FUNCTION pathways.p09_role_allows(text,text) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION pathways.p09_role_allows(text,text) TO pathways_runtime;

-- Configuration reads must not reveal beneficiary events or participations.
DROP POLICY p09_select ON pathways.beneficiary_journey_events;
CREATE POLICY p09_select ON pathways.beneficiary_journey_events AS RESTRICTIVE FOR SELECT TO pathways_runtime
USING(pathways.p05_has_project_permission('journeys.read',project_id)
 AND pathways.p05_has_project_permission('beneficiaries.records.read',project_id));
DROP POLICY p09_select ON pathways.beneficiary_activity_participations;
CREATE POLICY p09_select ON pathways.beneficiary_activity_participations AS RESTRICTIVE FOR SELECT TO pathways_runtime
USING(pathways.p05_has_project_permission('journeys.read',project_id)
 AND pathways.p05_has_project_permission('beneficiaries.records.read',project_id));

DROP POLICY p05_mapping_insert ON pathways.activity_journey_stage_mappings;
CREATE POLICY p05_mapping_insert ON pathways.activity_journey_stage_mappings FOR INSERT TO pathways_runtime
WITH CHECK(organization_id=pathways.runtime_context_organization() AND created_by_id=pathways.runtime_context_user()
 AND (pathways.p05_has_project_permission('journeys.manage',project_id)
 OR pathways.p05_has_project_permission('activities.create',project_id) OR pathways.p05_has_project_permission('activities.update',project_id)));
DROP POLICY p05_mapping_delete ON pathways.activity_journey_stage_mappings;
CREATE POLICY p05_mapping_delete ON pathways.activity_journey_stage_mappings FOR DELETE TO pathways_runtime
USING(pathways.p05_has_project_permission('journeys.manage',project_id) OR pathways.p05_has_project_permission('activities.update',project_id));

-- Only a boolean needed to preserve configuration freezes; no beneficiary data.
CREATE FUNCTION pathways.p10_journey_has_events(wanted_project uuid) RETURNS boolean
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$
BEGIN
 IF NOT pathways.p05_has_project_permission('journeys.manage',wanted_project) THEN
   RAISE EXCEPTION 'Journey configuration unavailable' USING ERRCODE='42501'; END IF;
 RETURN EXISTS(SELECT FROM pathways.beneficiary_journey_events e WHERE e.project_id=wanted_project
 AND e.organization_id=pathways.runtime_context_organization());
END $$;
REVOKE ALL ON FUNCTION pathways.p10_journey_has_events(uuid) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION pathways.p10_journey_has_events(uuid) TO pathways_runtime;

-- Admin import access is supporting access to its own imported submissions.
DROP POLICY p09_select ON pathways.form_submissions;
CREATE POLICY p09_select ON pathways.form_submissions AS RESTRICTIVE FOR SELECT TO pathways_runtime
USING(pathways.p05_has_project_permission('submissions.write',project_id)
 OR pathways.p05_has_project_permission('assessments.detail.read',project_id)
 OR (pathways.p05_has_project_permission('imports.process',project_id)
 AND import_batch_id IS NOT NULL AND submitted_by_id=pathways.runtime_context_user()));
DROP POLICY p09_select ON pathways.form_response_values;
CREATE POLICY p09_select ON pathways.form_response_values AS RESTRICTIVE FOR SELECT TO pathways_runtime
USING(pathways.p05_has_project_permission('submissions.write',project_id)
 OR pathways.p05_has_project_permission('assessments.detail.read',project_id)
 OR (pathways.p05_has_project_permission('imports.process',project_id) AND EXISTS(
 SELECT FROM pathways.form_submissions s WHERE s.id=submission_id AND s.project_id=pathways.form_response_values.project_id
 AND s.import_batch_id IS NOT NULL AND s.submitted_by_id=pathways.runtime_context_user())));

DROP POLICY p09_update ON pathways.project_evaluation_criteria;
CREATE POLICY p09_update ON pathways.project_evaluation_criteria AS RESTRICTIVE FOR UPDATE TO pathways_runtime
USING(pathways.p05_has_project_permission('evaluations.weights.configure',project_id))
WITH CHECK(pathways.p05_has_project_permission('evaluations.weights.configure',project_id));
CREATE FUNCTION pathways.p10_guard_evaluation_weight() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path='' AS $$
BEGIN
 IF current_user='pathways_runtime' AND NOT pathways.p09_can('settings.configure')
 AND to_jsonb(NEW)-ARRAY['weight_percentage','updated_at'] IS DISTINCT FROM to_jsonb(OLD)-ARRAY['weight_percentage','updated_at']
 THEN RAISE EXCEPTION 'Evaluation weight configuration cannot edit criterion definitions' USING ERRCODE='42501'; END IF;
 RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION pathways.p10_guard_evaluation_weight() FROM PUBLIC,anon,authenticated,service_role,pathways_runtime;
CREATE TRIGGER p10_evaluation_weight BEFORE UPDATE ON pathways.project_evaluation_criteria FOR EACH ROW EXECUTE FUNCTION pathways.p10_guard_evaluation_weight();

CREATE POLICY p10_evidence_select ON pathways.evidence_media AS RESTRICTIVE FOR SELECT TO pathways_runtime
USING(pathways.p05_has_project_permission('evidence.read',project_id));




-- Supporting activity context does not grant API activity screens or nested records.
DROP POLICY p05_activity_select ON pathways.project_activities;
CREATE POLICY p05_activity_select ON pathways.project_activities FOR SELECT TO pathways_runtime
USING (organization_id=pathways.runtime_context_organization()
 AND (pathways.p05_has_project_permission('activities.read',project_id)
 OR pathways.p05_has_project_permission('activities.context.read',project_id)
 OR pathways.p05_has_project_permission('participation.record',project_id)));

COMMIT;
