export enum AppRole {
  SYSTEM_ADMINISTRATOR = 'SYSTEM_ADMINISTRATOR',
  PROGRAM_MANAGER = 'PROGRAM_MANAGER',
  GRANT_MANAGER = 'GRANT_MANAGER',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  MONITORING_AND_EVALUATION_OFFICER = 'MONITORING_AND_EVALUATION_OFFICER',
  PROJECT_OFFICER = 'PROJECT_OFFICER',
}
