/** CSV RBAC contract, approved 2026-09-26. Database grants are authoritative;
 * this ceiling can only narrow them. No wildcard or administrator bypass.
 * See docs/rfc-pathways-auth-rbac-isolation.md for source precedence and scope.
 */
export const roleNames = {
  SYSTEM_ADMINISTRATOR: 'System Administrator',
  PROGRAM_MANAGER: 'Program Manager',
  GRANT_MANAGER: 'Grant Manager',
  PROJECT_MANAGER: 'Project Manager',
  MONITORING_AND_EVALUATION_OFFICER: 'Monitoring and Evaluation Officer',
  PROJECT_OFFICER: 'Project Officer',
} as const
export type CanonicalRole = keyof typeof roleNames

// Retired atomic codes remain recognized for migration history, with no grants.
export const permissionCodes = [
  'forms.archive',
  'indicators.archive',
  'milestones.manage',
  'assessments.detail.read',
  'settings.labels.manage',
  'programs.create',
  'projects.read',
  'projects.create',
  'activities.read',
  'activities.create',
  'activities.update',
  'activities.proof.submit',
  'journeys.read',
  'journeys.manage',
  'participation.record',
  'budgets.read',
  'budgets.create',
  'budgets.update',
  'expenses.read',
  'expenses.submit',
  'expenses.verify',
  'expenses.approve',
  'monitoring.read',
  'monitoring.review',
  'rules.read',
  'rules.create',
  'rules.update',
  'rules.activate',
  'alerts.read',
  'alerts.review',
  'alerts.outcome.record',
  'recommendations.read',
  'recommendations.review',
  'beneficiaries.records.read',
  'beneficiaries.records.register',
  'beneficiaries.profiles.update',
  'beneficiaries.enrollments.manage',
  'beneficiaries.identities.review',
  'beneficiaries.records.archive',
  'beneficiaries.aggregates.read',
  'recommendations.outcome.record',
  'evaluations.submit',
  'evaluations.approve',
  'public.preview',
  'public.publish',
  'evidence.review',
  'indicators.create',
  'indicators.update',
  'collection.read',
  'forms.read',
  'forms.manage',
  'forms.publish',
  'submissions.write',
  'imports.read',
  'imports.upload',
  'imports.review',
  'imports.process',
  'analytics.read',
  'reports.read',
  'reports.project.read',
  'reports.indicator.read',
  'reports.beneficiary.read',
  'users.authorize',
  'assignments.manage',
  'settings.read',
  'projects.detail.read',
  'projects.update',
  'projects.archive',
  'activities.complete',
  'expenses.evidence.submit',
  'indicators.read',
  'evaluations.archive',
  'evaluations.signoff',
  'assessments.read',
  'public.approve',
  'forms.generate',
  'forms.export',
  'forms.import',
  'imports.validate',
  'analytics.export',
  'reports.generate',
  'reports.export',
  'audit.read',
  'settings.configure',
  'backups.create',
  'backups.restore',
  'profile.manage',
  'expenses.signoff',
] as const
export type AtomicPermission = (typeof permissionCodes)[number]

export const rolePermissions: Record<CanonicalRole, readonly AtomicPermission[]> = {
  SYSTEM_ADMINISTRATOR: [
    'assessments.detail.read',
    'projects.read',
    'activities.read',
    'budgets.read',
    'monitoring.read',
    'monitoring.review',
    'rules.read',
    'rules.create',
    'rules.update',
    'rules.activate',
    'alerts.read',
    'alerts.review',
    'alerts.outcome.record',
    'recommendations.read',
    'recommendations.review',
    'beneficiaries.enrollments.manage',
    'beneficiaries.aggregates.read',
    'recommendations.outcome.record',
    'public.preview',
    'public.publish',
    'indicators.create',
    'indicators.update',
    'collection.read',
    'forms.read',
    'imports.read',
    'imports.upload',
    'imports.review',
    'imports.process',
    'analytics.read',
    'reports.read',
    'reports.project.read',
    'reports.indicator.read',
    'users.authorize',
    'assignments.manage',
    'settings.read',
    'projects.archive',
    'activities.complete',
    'indicators.read',
    'assessments.read',
    'public.approve',
    'forms.generate',
    'imports.validate',
    'analytics.export',
    'reports.generate',
    'reports.export',
    'audit.read',
    'settings.configure',
    'backups.create',
    'backups.restore',
    'profile.manage',
  ],
  PROJECT_OFFICER: [
    'imports.process',
    'assessments.detail.read',
    'projects.read',
    'activities.read',
    'activities.create',
    'activities.update',
    'activities.proof.submit',
    'journeys.read',
    'participation.record',
    'expenses.read',
    'expenses.submit',
    'beneficiaries.records.read',
    'beneficiaries.records.register',
    'beneficiaries.profiles.update',
    'beneficiaries.enrollments.manage',
    'collection.read',
    'forms.read',
    'forms.manage',
    'forms.publish',
    'submissions.write',
    'imports.read',
    'imports.upload',
    'reports.read',
    'reports.project.read',
    'reports.indicator.read',
    'reports.beneficiary.read',
    'settings.read',
    'activities.complete',
    'expenses.evidence.submit',
    'assessments.read',
    'forms.generate',
    'forms.export',
    'forms.import',
    'imports.validate',
    'reports.generate',
    'reports.export',
    'profile.manage',
  ],
  MONITORING_AND_EVALUATION_OFFICER: [
    'assessments.detail.read',
    'projects.read',
    'activities.read',
    'journeys.read',
    'participation.record',
    'budgets.read',
    'expenses.read',
    'expenses.submit',
    'expenses.verify',
    'monitoring.read',
    'monitoring.review',
    'alerts.read',
    'alerts.review',
    'alerts.outcome.record',
    'recommendations.read',
    'recommendations.review',
    'beneficiaries.records.read',
    'beneficiaries.records.register',
    'beneficiaries.profiles.update',
    'beneficiaries.enrollments.manage',
    'beneficiaries.aggregates.read',
    'recommendations.outcome.record',
    'evaluations.submit',
    'evidence.review',
    'indicators.create',
    'indicators.update',
    'collection.read',
    'forms.read',
    'forms.manage',
    'forms.publish',
    'submissions.write',
    'imports.read',
    'imports.upload',
    'imports.review',
    'imports.process',
    'analytics.read',
    'reports.read',
    'reports.project.read',
    'reports.indicator.read',
    'reports.beneficiary.read',
    'settings.read',
    'projects.detail.read',
    'activities.complete',
    'indicators.read',
    'evaluations.archive',
    'assessments.read',
    'forms.generate',
    'forms.export',
    'forms.import',
    'imports.validate',
    'analytics.export',
    'reports.generate',
    'reports.export',
    'profile.manage',
  ],
  PROJECT_MANAGER: [
    'assessments.detail.read',
    'projects.read',
    'projects.create',
    'activities.read',
    'activities.create',
    'activities.update',
    'activities.proof.submit',
    'journeys.read',
    'participation.record',
    'budgets.read',
    'budgets.create',
    'budgets.update',
    'expenses.read',
    'expenses.submit',
    'expenses.approve',
    'monitoring.read',
    'monitoring.review',
    'alerts.read',
    'alerts.review',
    'alerts.outcome.record',
    'recommendations.read',
    'recommendations.review',
    'beneficiaries.records.read',
    'beneficiaries.records.register',
    'beneficiaries.profiles.update',
    'beneficiaries.aggregates.read',
    'recommendations.outcome.record',
    'evaluations.approve',
    'public.preview',
    'public.publish',
    'indicators.create',
    'indicators.update',
    'forms.read',
    'analytics.read',
    'reports.read',
    'reports.project.read',
    'reports.indicator.read',
    'reports.beneficiary.read',
    'users.authorize',
    'assignments.manage',
    'settings.read',
    'projects.detail.read',
    'projects.update',
    'projects.archive',
    'activities.complete',
    'indicators.read',
    'assessments.read',
    'public.approve',
    'forms.generate',
    'analytics.export',
    'reports.generate',
    'reports.export',
    'audit.read',
    'profile.manage',
  ],
  PROGRAM_MANAGER: [
    'forms.read',
    'projects.read',
    'budgets.read',
    'budgets.create',
    'budgets.update',
    'expenses.read',
    'monitoring.read',
    'monitoring.review',
    'alerts.read',
    'alerts.review',
    'alerts.outcome.record',
    'recommendations.read',
    'recommendations.review',
    'beneficiaries.aggregates.read',
    'recommendations.outcome.record',
    'public.preview',
    'public.publish',
    'analytics.read',
    'reports.read',
    'reports.project.read',
    'reports.indicator.read',
    'users.authorize',
    'assignments.manage',
    'settings.read',
    'projects.detail.read',
    'projects.archive',
    'evaluations.signoff',
    'assessments.read',
    'public.approve',
    'forms.generate',
    'analytics.export',
    'reports.generate',
    'reports.export',
    'audit.read',
    'profile.manage',
    'expenses.signoff',
  ],
  GRANT_MANAGER: [
    'forms.read',
    'projects.read',
    'budgets.read',
    'budgets.create',
    'budgets.update',
    'expenses.read',
    'monitoring.read',
    'monitoring.review',
    'alerts.read',
    'alerts.review',
    'alerts.outcome.record',
    'recommendations.read',
    'recommendations.review',
    'beneficiaries.aggregates.read',
    'recommendations.outcome.record',
    'public.preview',
    'public.publish',
    'analytics.read',
    'reports.read',
    'reports.project.read',
    'reports.indicator.read',
    'settings.read',
    'projects.detail.read',
    'projects.archive',
    'evaluations.signoff',
    'assessments.read',
    'public.approve',
    'forms.generate',
    'analytics.export',
    'reports.generate',
    'reports.export',
    'profile.manage',
    'expenses.signoff',
  ],
}

export function isCanonicalRole(role: string): role is CanonicalRole {
  return Object.hasOwn(roleNames, role)
}

export function hasAtomicPermission(role: string, granted: readonly string[], permission: string) {
  return (
    isCanonicalRole(role) &&
    granted.includes(permission) &&
    rolePermissions[role].includes(permission as AtomicPermission)
  )
}

export const aggregateOnlyRoles: readonly string[] = ['PROGRAM_MANAGER', 'GRANT_MANAGER']

export function canAuthorizeRole(actor: CanonicalRole, target: CanonicalRole) {
  if (actor === 'SYSTEM_ADMINISTRATOR') return true
  if (actor === 'PROGRAM_MANAGER') {
    return ['PROJECT_MANAGER', 'MONITORING_AND_EVALUATION_OFFICER'].includes(target)
  }
  return (
    actor === 'PROJECT_MANAGER' &&
    ['PROJECT_OFFICER', 'MONITORING_AND_EVALUATION_OFFICER'].includes(target)
  )
}

export function canAssignRole(actor: CanonicalRole, target: CanonicalRole) {
  return (
    [
      'PROJECT_MANAGER',
      'PROJECT_OFFICER',
      'MONITORING_AND_EVALUATION_OFFICER',
      'GRANT_MANAGER',
    ].includes(target) && canAuthorizeRole(actor, target)
  )
}
